- hosts: localhost
  connection: local
  gather_facts: False

  vars:
    STATE_RES_NAME: "ami_info"
  tasks:

    - name: run cmd
      shell: |
        shipctl post_resource_state "{{ STATE_RES_NAME }}" versionName "build-{{ BUILD_NUMBER }}"

    - name: Create VPC {{ VPC_NAME }}
      ec2_vpc_net:
        name: "{{ VPC_NAME }}"
        cidr_block: "{{ VPC_CIDR_BLOCK }}"
        tags:
          module: "{{ VPC_NAME }}"
      register: vpc

    - name: run cmd
      shell: |
        shipctl post_resource_state "{{ STATE_RES_NAME }}" versionName "build-{{ BUILD_NUMBER }}"
        shipctl put_resource_state "{{ STATE_RES_NAME }}" VPC_ID "{{ vpc.vpc.id }}"